import { useState } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { useCreateInfluencer, useListInfluencers, getListInfluencersQueryKey, useUpdateInfluencer, useLinkInfluencerCoupon, useUnlinkInfluencerCoupon, useAdminListCoupons, getAdminListCouponsQueryKey } from '@workspace/api-client-react';
import { useLanguage } from '@/hooks/use-language';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Plus, UserRound, Power, Link2, Unlink } from 'lucide-react';

const blank = { name: '', email: '', password: '', referralCode: '', commissionRate: '10', imageUrl: '' };
export default function AdminInfluencers() {
  const { t, lang } = useLanguage(); const qc = useQueryClient();
  const list = useListInfluencers({ query: { retry: false, queryKey: getListInfluencersQueryKey() } });
  const coupons = useAdminListCoupons(undefined, { query: { queryKey: getAdminListCouponsQueryKey() } });
  const create = useCreateInfluencer(); const update = useUpdateInfluencer(); const link = useLinkInfluencerCoupon(); const unlink = useUnlinkInfluencerCoupon();
  const [open, setOpen] = useState(false); const [selected, setSelected] = useState<number | null>(null); const [form, setForm] = useState(blank); const [message, setMessage] = useState('');
  const [linked, setLinked] = useState<Record<number, number[]>>({});
  const refresh = () => qc.invalidateQueries({ queryKey: getListInfluencersQueryKey() });
  const save = (event: React.FormEvent) => { event.preventDefault(); setMessage(''); const data: any = { name: form.name, email: form.email, referralCode: form.referralCode, commissionRate: Number(form.commissionRate), imageUrl: form.imageUrl || null }; if (form.password) data.password = form.password;
    if (selected) update.mutate({ id: selected, data }, { onSuccess: () => { setSelected(null); setOpen(false); void refresh(); }, onError: () => setMessage(t('تعذر تحديث الحساب', 'Could not update account')) });
    else create.mutate({ data: { ...data, password: form.password } }, { onSuccess: () => { setForm(blank); setOpen(false); void refresh(); }, onError: () => setMessage(t('تعذر إنشاء الحساب', 'Could not create account')) }); };
  const edit = (item: any) => { setSelected(item.id); setForm({ name: item.name, email: item.email, password: '', referralCode: item.referralCode, commissionRate: String(item.commissionRate), imageUrl: item.imageUrl ?? '' }); setOpen(true); };
  return <div dir={lang === 'ar' ? 'rtl' : 'ltr'} className="space-y-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">{t('إدارة المشاهير', 'Influencer management')}</h1><p className="mt-1 text-sm text-muted-foreground">{t('الحسابات والإحالات والعمولات والأداء المدفوع', 'Accounts, referrals, commissions and paid performance')}</p></div><Button onClick={() => { setSelected(null); setForm(blank); setOpen(v => !v); }}><Plus className="me-2 h-4 w-4" />{t('مشهور جديد', 'New influencer')}</Button></div>
    {open && <form onSubmit={save} className="grid gap-4 rounded-xl border bg-card p-5 sm:grid-cols-2 lg:grid-cols-3">{([['name', t('الاسم', 'Name')], ['email', t('البريد الإلكتروني', 'Email')], ['password', selected ? t('كلمة مرور جديدة (اختياري)', 'New password (optional)') : t('كلمة المرور', 'Password')], ['referralCode', t('رمز الإحالة', 'Referral code')], ['commissionRate', t('نسبة العمولة %', 'Commission %')], ['imageUrl', t('رابط الصورة', 'Photo URL')]] as const).map(([key, label]) => <label key={key} className="text-sm font-medium">{label}<Input className="mt-2" required={!selected && ['name', 'email', 'password', 'referralCode'].includes(key)} type={key === 'password' ? 'password' : key === 'commissionRate' ? 'number' : key === 'email' ? 'email' : 'text'} dir={key === 'name' ? undefined : 'ltr'} value={form[key]} onChange={e => setForm({ ...form, [key]: e.target.value })} /></label>)}<div className="flex items-end gap-2 sm:col-span-2 lg:col-span-3"><Button disabled={create.isPending || update.isPending}>{t('حفظ', 'Save')}</Button><Button type="button" variant="outline" onClick={() => setOpen(false)}>{t('إلغاء', 'Cancel')}</Button>{message && <span className="text-sm text-destructive">{message}</span>}</div></form>}
    {list.isLoading && <div className="rounded-xl border bg-card p-10 text-center text-muted-foreground">{t('جاري التحميل…', 'Loading…')}</div>}{list.error && <div className="rounded-xl border border-destructive/30 bg-card p-10 text-center text-destructive">{t('تعذر تحميل المشاهير', 'Could not load influencers')}</div>}{!list.isLoading && !list.error && !list.data?.length && <div className="rounded-xl border bg-card p-10 text-center text-muted-foreground"><UserRound className="mx-auto mb-3 h-8 w-8" />{t('لا توجد حسابات بعد', 'No accounts yet')}</div>}
    {!!list.data?.length && <section className="overflow-x-auto rounded-xl border bg-card"><table className="w-full text-sm"><thead className="border-b bg-muted/40"><tr>{['المشهور|Influencer','الأداء المدفوع|Paid performance','الإحالة|Referral','الحالة|Status','إجراءات|Actions'].map(x => <th className="p-4 text-start" key={x}>{t(...x.split('|') as [string,string])}</th>)}</tr></thead><tbody>{list.data.map((item: any) => <tr className="border-b align-top last:border-0" key={item.id}><td className="p-4"><div className="flex items-center gap-3">{item.imageUrl ? <img src={item.imageUrl} alt="" className="h-9 w-9 rounded-full object-cover" /> : <div className="grid h-9 w-9 place-items-center rounded-full bg-muted"><UserRound className="h-4 w-4" /></div>}<div><p className="font-medium">{item.name}</p><p className="text-xs text-muted-foreground" dir="ltr">{item.email}</p></div></div></td><td className="p-4 text-xs"><p>{item.performance?.orders ?? 0} {t('طلب', 'orders')}</p><p>{Number(item.performance?.sales ?? 0).toLocaleString()} SAR</p><p className="text-emerald-600">{Number(item.performance?.commission ?? 0).toLocaleString()} SAR {t('عمولة', 'commission')}</p></td><td className="p-4"><p className="font-mono" dir="ltr">{item.referralCode}</p><p>{item.commissionRate}%</p><select className="mt-2 max-w-[150px] rounded border bg-card p-1 text-xs" value="" onChange={e => { const couponId = Number(e.target.value); if (couponId) link.mutate({ id: item.id, data: { couponId } }, { onSuccess: () => { setLinked(v => ({ ...v, [item.id]: [...(v[item.id] ?? []), couponId] })); void refresh(); } }); }}><option value="">{t('ربط كوبون…', 'Link coupon…')}</option>{(coupons.data ?? []).filter((c: any) => c.isActive).map((c: any) => <option value={c.id} key={c.id}>{c.code}</option>)}</select></td><td className="p-4"><Badge variant={item.isActive === false ? 'secondary' : 'default'}>{item.isActive === false ? t('غير فعال', 'Inactive') : t('فعال', 'Active')}</Badge></td><td className="p-4"><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => update.mutate({ id: item.id, data: { isActive: item.isActive === false } }, { onSuccess: refresh })}><Power className="me-1 h-3.5 w-3.5" />{item.isActive === false ? t('تفعيل', 'Activate') : t('تعطيل', 'Deactivate')}</Button><Button size="sm" variant="ghost" onClick={() => edit(item)}>{t('تعديل', 'Edit')}</Button></div><div className="mt-2 flex flex-wrap gap-1">{(coupons.data ?? []).filter((c: any) => [...(item.couponIds ?? []), ...(linked[item.id] ?? [])].includes(c.id)).map((c: any) => <button key={c.id} className="rounded bg-muted px-2 py-1 text-xs" onClick={() => unlink.mutate({ id: item.id, couponId: c.id }, { onSuccess: () => { setLinked(v => ({ ...v, [item.id]: (v[item.id] ?? []).filter(id => id !== c.id) })); void refresh(); } })}>{c.code} <Unlink className="ms-1 inline h-3 w-3" /></button>)}</div></td></tr>)}</tbody></table></section>}
  </div>;
}