import { useMemo, useState } from 'react';
import { Link } from 'wouter';
import { useQueryClient } from '@tanstack/react-query';
import { type AdminSocialPost, getAdminListSocialPostsQueryKey, useAdminListSocialPosts, useAdminListCampaigns, useAdminGetCampaignResults, useAdminDeleteSocialPost, useAdminMarkSocialPostPublishedManually, useGetAdminMe } from '@workspace/api-client-react';
import { ArrowRight, ArrowUpRight, CalendarClock, ChevronLeft, ChevronRight, CircleCheck, Clock3, FilePenLine, LockKeyhole, MoreHorizontal, Plus, Search, ShieldCheck, Trash2, WifiOff } from 'lucide-react';
import { useLanguage } from '@/hooks/use-language';
import { useToast } from '@/hooks/use-toast';
import { hasPermission } from '@/lib/permissions';
import { Money } from '@/components/money';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import { Composer, displayDate, EmptyBlock, LoadBlock, MarketingImage, MarketingShell, PlatformTags, platforms, platformName, Status } from './shared';

function useAccess() {
  const { data: user } = useGetAdminMe();
  return { canEdit: hasPermission(user, 'campaigns', 'edit'), canDelete: hasPermission(user, 'campaigns', 'delete') };
}
function ManualNote() {
  const { t } = useLanguage();
  return <div className="flex gap-3 rounded-xl border border-accent/25 bg-accent/5 px-4 py-3 text-sm text-muted-foreground"><CalendarClock className="mt-0.5 h-4 w-4 shrink-0 text-accent" /><p><strong className="text-foreground">{t('خطة تحريرية، وليست نشراً تلقائياً.', 'An editorial plan, not automatic publishing.')} </strong>{t('انشر المحتوى بنفسك على المنصة، ثم علّمه كمنشور يدوياً.', 'Publish on the platform yourself, then mark it as manually published.')}</p></div>;
}
function NewButton({ onClick }: { onClick: () => void }) {
  const { t } = useLanguage();
  return <Button onClick={onClick} data-testid="button-new-social-post" className="w-full shrink-0 sm:w-auto"><Plus className="me-2 h-4 w-4" />{t('محتوى جديد', 'New content')}</Button>;
}

export function MarketingOverview() {
  const { t, lang } = useLanguage();
  const { canEdit } = useAccess();
  const posts = useAdminListSocialPosts();
  const campaigns = useAdminListCampaigns();
  const results = useAdminGetCampaignResults({});
  const [open, setOpen] = useState(false);
  const records = posts.data ?? [];
  const upcoming = records.filter(p => p.status === 'scheduled' && p.scheduledAt).sort((a, b) => new Date(a.scheduledAt!).getTime() - new Date(b.scheduledAt!).getTime()).slice(0, 4);
  const activeCampaigns = campaigns.data?.filter(c => c.status === 'active' && new Date(c.startsAt).getTime() <= Date.now() && new Date(c.endsAt).getTime() >= Date.now()) ?? [];
  return <MarketingShell title={t('مساحة التسويق', 'Marketing workspace')} eyebrow="Overview" description={t('مكان واحد لتخطيط المحتوى ومتابعة الحملات، بلا وعود نشر غير متاحة.', 'Plan content and follow campaign outcomes in one place, without promising unavailable publishing.')} action={canEdit && <NewButton onClick={() => setOpen(true)} />}>
    <LoadBlock loading={posts.isLoading || campaigns.isLoading} error={posts.isError || campaigns.isError} retry={() => { posts.refetch(); campaigns.refetch(); }}>
      <div className="mk-hero grid gap-8 p-6 sm:p-8 lg:grid-cols-[1.5fr_1fr] lg:p-10">
        <div className="relative z-10"><span className="text-[10px] font-bold uppercase tracking-[.25em] text-[#d9b95f]">{t('غرفة العمليات / ٠١', 'THE EDITORIAL DESK / 01')}</span><h2 className="mk-display mt-5 max-w-xl text-4xl leading-[1.15] sm:text-5xl">{t('كل فكرة لها مكان. وكل منشور له موعد.', 'A place for every idea. A plan for every post.')}</h2><p className="mt-5 max-w-lg text-sm leading-7 text-[#c8c5b9]">{t('رتّب رسائل العلامة وصورها وجدولها، ثم تولّى النشر على قنواتك يدوياً.', 'Organize brand stories, assets and dates. Your team handles publication on each channel manually.')}</p><Link href="/admin/marketing/content" data-testid="link-overview-content" className="mt-7 inline-flex items-center gap-2 border-b border-[#d9b95f] pb-1 text-sm font-semibold text-[#e5cc83]">{t('استعرض مكتبة المحتوى', 'Explore content library')}<ArrowUpRight className="h-4 w-4" /></Link></div>
        <div className="relative z-10 flex flex-col justify-end border-t border-[#ffffff30] pt-5 lg:border-s lg:border-t-0 lg:ps-8"><span className="text-xs font-semibold text-[#d9b95f]">{t('النشر القادم يدوياً', 'NEXT MANUAL PUBLICATION')}</span>{upcoming.length ? <><span className="mt-3 line-clamp-2 text-2xl font-semibold">{upcoming[0].title}</span><span className="mt-2 text-sm text-[#c8c5b9]">{displayDate(upcoming[0].scheduledAt, lang, { day: 'numeric', month: 'long', hour: '2-digit', minute: '2-digit' })}</span><PlatformTags items={upcoming[0].platforms} /></> : <p className="mt-3 text-sm leading-6 text-[#c8c5b9]">{t('لا توجد منشورات مخططة بعد. ابدأ بمسودة أو اختر موعداً للنشر.', 'No planned posts yet. Start with a draft or choose a publication date.')}</p>}</div>
      </div>
      <div className="mk-surface grid grid-cols-2 gap-5 p-5 md:grid-cols-4 md:p-7">
        {[{ label: t('إجمالي المحتوى', 'Total pieces'), value: records.length, icon: FilePenLine }, { label: t('مسودات', 'Drafts'), value: records.filter(p => p.status === 'draft').length, icon: Clock3 }, { label: t('مخطط للنشر', 'Planned'), value: records.filter(p => p.status === 'scheduled').length, icon: CalendarClock }, { label: t('نُشر يدوياً', 'Manually published'), value: records.filter(p => p.status === 'published_manual').length, icon: CircleCheck }].map((metric, i) => <div key={i} className="mk-stat" data-testid={`metric-marketing-${i}`}><metric.icon className="mb-4 h-4 w-4 text-accent" /><div className="mk-display text-4xl leading-none">{metric.value.toLocaleString(lang === 'ar' ? 'ar-SA-u-nu-latn' : 'en-GB')}</div><div className="mt-2 text-xs text-muted-foreground">{metric.label}</div></div>)}
      </div>
      <div className="grid gap-5 lg:grid-cols-[1.35fr_1fr]">
        <section className="mk-surface overflow-hidden"><div className="flex items-center justify-between border-b border-border p-5"><div><h2 className="font-bold">{t('جدول النشر القادم', 'Upcoming editorial plan')}</h2><p className="mt-1 text-xs text-muted-foreground">{t('مواعيد مستهدفة للنشر اليدوي', 'Target dates for manual publishing')}</p></div><Link href="/admin/marketing/calendar" data-testid="link-overview-calendar" className="text-xs font-semibold text-accent hover:underline">{t('التقويم', 'Calendar')} <ArrowRight className="inline h-3 w-3" /></Link></div>{upcoming.length ? upcoming.map(p => <div key={p.id} className="flex gap-4 border-b border-border/70 p-5 last:border-0"><div className="flex w-12 shrink-0 flex-col items-center justify-center rounded-lg bg-muted p-2"><span className="text-xl font-bold">{new Date(p.scheduledAt!).getDate()}</span><span className="text-[10px] uppercase text-muted-foreground">{displayDate(p.scheduledAt, lang, { month: 'short' })}</span></div><div className="min-w-0 flex-1"><div className="truncate text-sm font-semibold">{p.title}</div><div className="mt-1 text-xs text-muted-foreground">{displayDate(p.scheduledAt, lang, { hour: '2-digit', minute: '2-digit' })}</div><div className="mt-2"><PlatformTags items={p.platforms} /></div></div><Status status={p.status} /></div>) : <div className="p-8 text-center text-sm text-muted-foreground">{t('لا يوجد محتوى مجدول. أضف موعداً من المحرر.', 'No planned content. Add a date in the composer.')}</div>}</section>
        <section className="mk-surface overflow-hidden"><div className="flex items-center justify-between border-b border-border p-5"><div><h2 className="font-bold">{t('الحملات', 'Campaigns')}</h2><p className="mt-1 text-xs text-muted-foreground">{t('حملات نشطة فعلياً في هذه اللحظة', 'Campaigns active right now')}</p></div><Link href="/admin/marketing" data-testid="link-overview-campaigns" className="text-xs font-semibold text-accent hover:underline">{t('إدارة الحملات', 'Manage')} <ArrowRight className="inline h-3 w-3" /></Link></div><div className="p-5">{activeCampaigns.length ? activeCampaigns.slice(0, 3).map(c => <div key={c.id} className="border-b border-border py-3 first:pt-0 last:border-0"><div className="font-semibold">{c.name}</div><div className="mt-1 text-xs text-muted-foreground">{displayDate(c.endsAt, lang)} · {t('حتى نهاية الحملة', 'Campaign end')}</div></div>) : <p className="py-6 text-center text-sm text-muted-foreground">{t('لا توجد حملات نشطة حالياً.', 'No active campaigns right now.')}</p>}</div><div className="border-t border-border bg-muted/30 p-5"><p className="text-xs font-semibold text-muted-foreground">{t('نتائج حملات المتجر', 'STOREFRONT CAMPAIGN RESULTS')}</p>{results.isLoading ? <div className="mk-shimmer mt-3 h-8 w-32 rounded" /> : results.isError ? <div className="mt-2 text-xs text-destructive">{t('تعذر تحميل النتائج.', 'Results unavailable.')} <button type="button" data-testid="button-retry-campaign-results" onClick={() => results.refetch()} className="underline">{t('إعادة المحاولة', 'Retry')}</button></div> : <div className="mt-2 flex flex-wrap items-end gap-x-4 gap-y-1"><span className="mk-display text-3xl"><Money value={results.data?.revenue ?? 0} lang={lang} /></span><span className="pb-1 text-xs text-muted-foreground">{results.data?.orders ?? 0} {t('طلبات منسوبة لكوبونات الحملات', 'coupon-attributed orders')}</span></div>}<p className="mt-2 text-[11px] text-muted-foreground">{t('إيراد وطلبات كوبونات المتجر، وليس تحليلات الشبكات الاجتماعية.', 'Store coupon revenue and orders, not social platform analytics.')}</p></div></section>
      </div><ManualNote />
    </LoadBlock><Composer open={open} onOpenChange={setOpen} />
  </MarketingShell>;
}

export function MarketingContent() {
  const { t, lang } = useLanguage();
  const { toast } = useToast();
  const client = useQueryClient();
  const { canEdit, canDelete } = useAccess();
  const query = useAdminListSocialPosts();
  const campaigns = useAdminListCampaigns();
  const remove = useAdminDeleteSocialPost();
  const mark = useAdminMarkSocialPostPublishedManually();
  const [open, setOpen] = useState(false);
  const [editing, setEditing] = useState<AdminSocialPost | null>(null);
  const [search, setSearch] = useState('');
  const [filter, setFilter] = useState('all');
  const [channel, setChannel] = useState('all');
  const items = useMemo(() => (query.data ?? []).filter(p => (filter === 'all' || p.status === filter) && (channel === 'all' || p.platforms.includes(channel as typeof platforms[number])) && `${p.title} ${p.caption}`.toLocaleLowerCase().includes(search.toLocaleLowerCase())).sort((a, b) => new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime()), [query.data, filter, channel, search]);
  const campaignName = (id: number | null) => id === null ? null : campaigns.data?.find(c => c.id === id)?.name ?? null;
  const refresh = () => client.invalidateQueries({ queryKey: getAdminListSocialPostsQueryKey() });
  const onError = () => toast({ title: t('تعذر إتمام العملية', 'Action failed'), variant: 'destructive' });
  const deletePost = (post: AdminSocialPost) => { if (!window.confirm(t(`حذف "${post.title}" نهائياً؟`, `Permanently delete "${post.title}"?`))) return; remove.mutate({ id: post.id }, { onSuccess: () => { refresh(); toast({ title: t('تم حذف المحتوى', 'Content deleted') }); }, onError }); };
  const publish = (post: AdminSocialPost) => { if (!window.confirm(t(`هل نشرت "${post.title}" بنفسك على القنوات المحددة بالفعل؟`, `Have you actually published "${post.title}" on the selected platforms yourself?`))) return; mark.mutate({ id: post.id }, { onSuccess: () => { refresh(); toast({ title: t('تم توثيق النشر اليدوي', 'Manual publication recorded') }); }, onError }); };
  return <MarketingShell title={t('مكتبة المحتوى', 'Content library')} eyebrow="Content" description={t('صياغة ومراجعة وجدولة المحتوى قبل نشره يدوياً.', 'Write, review and schedule content before publishing it manually.')} action={canEdit && <NewButton onClick={() => { setEditing(null); setOpen(true); }} />}>
    <ManualNote />
    <div className="mk-surface flex flex-col gap-3 p-4 lg:flex-row lg:items-center">
      <div className="relative min-w-0 flex-1"><Search className="absolute start-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input data-testid="input-search-social-posts" aria-label={t('بحث في المحتوى', 'Search content')} className="ps-10" value={search} onChange={e => setSearch(e.target.value)} placeholder={t('ابحث بالعنوان أو النص...', 'Search title or caption...')} /></div>
      <div className="flex gap-2"><Select value={filter} onValueChange={setFilter}><SelectTrigger data-testid="select-filter-status" aria-label={t('تصفية حسب الحالة', 'Filter status')} className="min-w-0 flex-1 lg:w-44"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">{t('كل الحالات', 'All statuses')}</SelectItem><SelectItem value="draft">{t('مسودات', 'Drafts')}</SelectItem><SelectItem value="scheduled">{t('مخطط', 'Planned')}</SelectItem><SelectItem value="published_manual">{t('منشور يدوياً', 'Manually published')}</SelectItem></SelectContent></Select><Select value={channel} onValueChange={setChannel}><SelectTrigger data-testid="select-filter-platform" aria-label={t('تصفية حسب القناة', 'Filter platform')} className="min-w-0 flex-1 lg:w-44"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">{t('كل القنوات', 'All platforms')}</SelectItem>{platforms.map(p => <SelectItem key={p} value={p}>{platformName[p]}</SelectItem>)}</SelectContent></Select></div>
    </div>
    <LoadBlock loading={query.isLoading} error={query.isError} retry={() => query.refetch()}>
      <div className="flex items-center justify-between"><h2 className="text-sm font-semibold">{t('المحتوى', 'Content')} <span className="ms-2 text-muted-foreground">{items.length}</span></h2><span className="text-xs text-muted-foreground">{t('الأحدث تعديلاً أولاً', 'Recently edited first')}</span></div>
      {items.length ? <div className="grid gap-3 lg:grid-cols-2">{items.map(p => <article key={p.id} data-testid={`card-social-post-${p.id}`} className="mk-surface mk-card-hover flex min-w-0 gap-4 p-4 sm:p-5">
        <div className="hidden h-28 w-24 shrink-0 overflow-hidden rounded-lg bg-muted sm:block">{p.mediaUrls[0] ? <MarketingImage src={p.mediaUrls[0]} alt="" className="h-full w-full object-cover" /> : <div className="flex h-full items-center justify-center"><FilePenLine className="h-6 w-6 text-muted-foreground/50" /></div>}</div>
        <div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><Status status={p.status} />{p.status !== 'published_manual' && (canEdit || canDelete) && <DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" className="h-8 w-8 shrink-0" aria-label={t('إجراءات المحتوى', 'Content actions')} data-testid={`button-post-actions-${p.id}`}><MoreHorizontal className="h-4 w-4" /></Button></DropdownMenuTrigger><DropdownMenuContent align="end">
          {canEdit && <DropdownMenuItem data-testid={`button-edit-post-${p.id}`} onClick={() => { setEditing(p); setOpen(true); }}><FilePenLine className="me-2 h-4 w-4" />{t('تعديل', 'Edit')}</DropdownMenuItem>}
          {canEdit && <DropdownMenuItem data-testid={`button-mark-published-${p.id}`} disabled={mark.isPending} onClick={() => publish(p)}><CircleCheck className="me-2 h-4 w-4" />{t('تأكيد النشر اليدوي', 'Confirm manual publication')}</DropdownMenuItem>}
          {canDelete && <><DropdownMenuSeparator /><DropdownMenuItem data-testid={`button-delete-post-${p.id}`} disabled={remove.isPending} className="text-destructive" onClick={() => deletePost(p)}><Trash2 className="me-2 h-4 w-4" />{t('حذف', 'Delete')}</DropdownMenuItem></>}
        </DropdownMenuContent></DropdownMenu>}</div><h3 className="mt-2 truncate font-semibold">{p.title}</h3><p className="mt-1 line-clamp-2 whitespace-pre-wrap text-xs leading-5 text-muted-foreground">{p.caption}</p><div className="mt-4"><PlatformTags items={p.platforms} /></div><div className="mt-4 flex flex-wrap items-center gap-x-3 gap-y-1 border-t border-border/70 pt-3 text-[11px] text-muted-foreground"><span>{p.status === 'scheduled' ? displayDate(p.scheduledAt, lang, { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' }) : p.status === 'published_manual' ? displayDate(p.publishedAt, lang) : displayDate(p.updatedAt, lang)}</span>{campaignName(p.campaignId) && <span>{campaignName(p.campaignId)}</span>}{p.mediaUrls.length > 0 && <span>{p.mediaUrls.length} {t('صور', 'images')}</span>}</div></div>
      </article>)}</div> : <EmptyBlock title={query.data?.length ? t('لا توجد نتائج مطابقة', 'No matching content') : t('كل قصة تبدأ بمسودة', 'Every story begins with a draft')} description={query.data?.length ? t('جرّب تغيير البحث أو التصفية.', 'Try a different search or filter.') : t('أنشئ أول قطعة محتوى وجهّزها لفريق النشر.', 'Create your first piece of content for the publishing team.')} action={canEdit && !query.data?.length && <NewButton onClick={() => { setEditing(null); setOpen(true); }} />} />}
    </LoadBlock><Composer open={open} onOpenChange={setOpen} post={editing} />
  </MarketingShell>;
}

export function MarketingCalendar() {
  const { t, lang } = useLanguage();
  const { canEdit } = useAccess();
  const query = useAdminListSocialPosts();
  const [month, setMonth] = useState(() => new Date(new Date().getFullYear(), new Date().getMonth(), 1));
  const [open, setOpen] = useState(false);
  const [date, setDate] = useState<Date | null>(null);
  const [editing, setEditing] = useState<AdminSocialPost | null>(null);
  const year = month.getFullYear(), monthIndex = month.getMonth();
  const startOffset = new Date(year, monthIndex, 1).getDay();
  const days = new Date(year, monthIndex + 1, 0).getDate();
  const cells = Array.from({ length: Math.ceil((startOffset + days) / 7) * 7 }, (_, i) => i - startOffset + 1);
  const byDay = (n: number) => (query.data ?? []).filter(p => p.status === 'scheduled' && p.scheduledAt && new Date(p.scheduledAt).getFullYear() === year && new Date(p.scheduledAt).getMonth() === monthIndex && new Date(p.scheduledAt).getDate() === n).sort((a, b) => new Date(a.scheduledAt!).getTime() - new Date(b.scheduledAt!).getTime());
  const agenda = (query.data ?? []).filter(p => p.status === 'scheduled' && p.scheduledAt && new Date(p.scheduledAt).getFullYear() === year && new Date(p.scheduledAt).getMonth() === monthIndex).sort((a, b) => new Date(a.scheduledAt!).getTime() - new Date(b.scheduledAt!).getTime());
  const move = (n: number) => setMonth(new Date(year, monthIndex + n, 1));
  const newFor = (day: number) => { if (!canEdit) return; setEditing(null); setDate(new Date(year, monthIndex, day, 10, 0)); setOpen(true); };
  const edit = (p: AdminSocialPost) => { if (!canEdit) return; setEditing(p); setDate(null); setOpen(true); };
  return <MarketingShell title={t('تقويم المحتوى', 'Editorial calendar')} eyebrow="Calendar" description={t('رؤية واضحة للمواعيد المخططة. النشر يتم يدوياً خارج هذه المساحة.', 'A clear view of planned dates. Publishing happens manually outside this workspace.')} action={canEdit && <NewButton onClick={() => { setEditing(null); setDate(null); setOpen(true); }} />}>
    <ManualNote />
    <LoadBlock loading={query.isLoading} error={query.isError} retry={() => query.refetch()}>
      <div className="mk-surface overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-border p-4 sm:p-5"><div><span className="text-[10px] font-bold uppercase tracking-[.2em] text-accent">{t('الجدول التحريري', 'EDITORIAL SCHEDULE')}</span><h2 className="mt-1 text-xl font-semibold">{month.toLocaleDateString(lang === 'ar' ? 'ar-SA-u-nu-latn' : 'en-GB', { month: 'long', year: 'numeric' })}</h2></div><div className="flex gap-1"><Button variant="outline" size="icon" aria-label={t('الشهر السابق', 'Previous month')} data-testid="button-previous-month" onClick={() => move(-1)}><ChevronLeft className={`h-4 w-4 ${lang === 'ar' ? 'rotate-180' : ''}`} /></Button><Button variant="outline" size="sm" data-testid="button-current-month" onClick={() => setMonth(new Date(new Date().getFullYear(), new Date().getMonth(), 1))}>{t('اليوم', 'Today')}</Button><Button variant="outline" size="icon" aria-label={t('الشهر القادم', 'Next month')} data-testid="button-next-month" onClick={() => move(1)}><ChevronRight className={`h-4 w-4 ${lang === 'ar' ? 'rotate-180' : ''}`} /></Button></div></div>
        <div className="grid grid-cols-7 border-b border-border bg-muted/35">{Array.from({ length: 7 }, (_, i) => <div key={i} className="px-1 py-3 text-center text-[10px] font-bold uppercase tracking-wide text-muted-foreground">{new Date(2024, 0, 7 + i).toLocaleDateString(lang === 'ar' ? 'ar-SA' : 'en-GB', { weekday: 'short' })}</div>)}</div>
        <div className="grid grid-cols-7">{cells.map((day, i) => <div key={i} className={`mk-calendar-cell group ${day < 1 || day > days ? 'bg-muted/25' : ''} ${day === new Date().getDate() && monthIndex === new Date().getMonth() && year === new Date().getFullYear() ? 'bg-accent/5' : ''}`}>{day >= 1 && day <= days && <><div className="flex items-center justify-between"><span className={`flex h-6 w-6 items-center justify-center rounded-full text-xs ${day === new Date().getDate() && monthIndex === new Date().getMonth() && year === new Date().getFullYear() ? 'bg-accent font-bold text-accent-foreground' : 'text-muted-foreground'}`}>{day}</span>{canEdit && <button type="button" data-testid={`button-add-calendar-${day}`} onClick={() => newFor(day)} aria-label={t(`أضف محتوى ليوم ${day}`, `Add content for day ${day}`)} className="rounded p-1 text-muted-foreground opacity-60 hover:bg-muted hover:text-foreground focus-visible:opacity-100 md:opacity-0 md:group-hover:opacity-100"><Plus className="h-3 w-3" /></button>}</div><div className="mt-2 space-y-1">{byDay(day).slice(0, 2).map(p => <button type="button" key={p.id} data-testid={`button-calendar-post-${p.id}`} onClick={() => edit(p)} className="block w-full truncate rounded bg-accent/10 px-1.5 py-1 text-start text-[10px] font-semibold text-foreground hover:bg-accent/20" title={p.title}>{p.title}</button>)}{byDay(day).length > 2 && <span className="block text-[10px] text-muted-foreground">+{byDay(day).length - 2}</span>}</div></>}</div>)}</div>
      </div>
      <section className="mk-surface overflow-hidden"><div className="border-b border-border p-5"><h2 className="font-bold">{t('أجندة الشهر', 'This month’s agenda')}</h2><p className="mt-1 text-xs text-muted-foreground">{agenda.length} {t('منشورات مخططة للنشر اليدوي', 'posts planned for manual publication')}</p></div>{agenda.length ? <div className="divide-y divide-border">{agenda.map(p => <div key={p.id} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:gap-5"><div className="w-24 shrink-0 text-xs font-semibold text-accent">{displayDate(p.scheduledAt, lang, { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' })}</div><div className="min-w-0 flex-1"><div className="truncate text-sm font-semibold">{p.title}</div><div className="mt-1"><PlatformTags items={p.platforms} /></div></div><Status status={p.status} />{canEdit && <Button variant="ghost" size="sm" data-testid={`button-edit-calendar-post-${p.id}`} onClick={() => edit(p)}>{t('تعديل', 'Edit')}</Button>}</div>)}</div> : <div className="p-10 text-center text-sm text-muted-foreground">{t('لا يوجد محتوى مخطط لهذا الشهر.', 'No content planned for this month.')}</div>}</section>
    </LoadBlock><Composer open={open} onOpenChange={setOpen} post={editing} date={date} />
  </MarketingShell>;
}

export function MarketingChannels() {
  const { t } = useLanguage();
  const query = useAdminListSocialPosts();
  const counts = (name: typeof platforms[number]) => (query.data ?? []).filter(p => p.platforms.includes(name)).length;
  return <MarketingShell title={t('القنوات والجاهزية', 'Channels & readiness')} eyebrow="Channels" description={t('حالة واضحة للقنوات المدعومة في التخطيط، وما يلزم قبل تشغيل النشر التلقائي.', 'An honest view of supported planning channels and what automatic publishing would require.')}>
    <div className="mk-hero p-6 sm:p-9"><div className="relative z-10 max-w-2xl"><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-[#d9b95f55] px-3 py-1 text-xs font-semibold text-[#e5cc83]"><WifiOff className="h-3.5 w-3.5" />{t('لا توجد حسابات اجتماعية متصلة', 'No social accounts connected')}</div><h2 className="mk-display text-4xl leading-tight sm:text-5xl">{t('التخطيط جاهز. الاتصال ليس بعد.', 'The plan is ready. Connections are not.')}</h2><p className="mt-5 text-sm leading-7 text-[#c8c5b9]">{t('يمكن لفريقك إعداد المحتوى وجدولته هنا ثم نشره بنفسه. لا يرسل هذا النظام المنشورات تلقائياً ولا يسحب تحليلات من منصات التواصل.', 'Your team can prepare and plan content here, then publish it themselves. This workspace does not auto-publish posts or pull analytics from social providers.')}</p></div></div>
    <LoadBlock loading={query.isLoading} error={query.isError} retry={() => query.refetch()}>
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{platforms.map((p, i) => <div key={p} className="mk-surface mk-card-hover flex flex-col justify-between p-5" data-testid={`card-channel-${p}`}><div><div className="flex items-start justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-xl border border-border bg-muted text-sm font-bold">{platformName[p].slice(0, 2).toUpperCase()}</span><span className="mk-status mk-status-draft">{t('غير متصل', 'Not connected')}</span></div><h3 className="mt-6 text-lg font-semibold">{platformName[p]}</h3><p className="mt-1 text-xs leading-5 text-muted-foreground">{t('متاح كوجهة في خطة المحتوى. يتولى الفريق النشر على المنصة يدوياً.', 'Available as a content planning destination. Your team publishes on the platform manually.')}</p></div><div className="mt-6 flex items-center justify-between border-t border-border pt-4 text-xs"><span className="text-muted-foreground">{t('قطع المحتوى المخططة', 'Content pieces')}</span><span className="font-semibold">{counts(p)}</span></div><div className="sr-only">{i}</div></div>)}</div>
    </LoadBlock>
    <div className="grid gap-5 lg:grid-cols-[1.2fr_1fr]"><section className="mk-surface p-6 sm:p-7"><div className="mb-5 flex items-center gap-3"><div className="rounded-xl bg-accent/10 p-2.5"><LockKeyhole className="h-5 w-5 text-accent" /></div><h2 className="text-lg font-semibold">{t('ما يلزم للنشر التلقائي', 'What automatic publishing requires')}</h2></div><div className="space-y-5">{[{ title: t('تصاريح من كل مزود', 'Provider permissions'), detail: t('موافقة التطبيقات ونطاقات الوصول المناسبة من Meta وTikTok وX وLinkedIn.', 'App approval and appropriate access scopes from Meta, TikTok, X and LinkedIn.') }, { title: t('ربط حسابات آمن', 'Secure account authorization'), detail: t('تدفق مصادقة وحفظ رموز وصول محمية لكل حساب، مع التعامل مع انتهاء صلاحيتها.', 'Authorization flow and secure token storage per account, including expiry handling.') }, { title: t('تنفيذ ومراقبة', 'Publishing and monitoring'), detail: t('خدمة نشر خلفية، إعادة المحاولة، سجل إخفاقات واضح، ومزامنة حالة النشر.', 'Background publishing, retries, clear failure logs and publication status synchronization.') }].map((step, i) => <div className="flex gap-4" key={i}><span className="mk-display shrink-0 text-2xl text-accent">0{i + 1}</span><div><h3 className="text-sm font-semibold">{step.title}</h3><p className="mt-1 text-xs leading-6 text-muted-foreground">{step.detail}</p></div></div>)}</div></section><section className="mk-surface flex flex-col justify-between p-6 sm:p-7"><div><ShieldCheck className="h-6 w-6 text-accent" /><h2 className="mt-5 text-lg font-semibold">{t('حدود البيانات بوضوح', 'Clear data boundaries')}</h2><p className="mt-3 text-sm leading-7 text-muted-foreground">{t('علامة «نُشر يدوياً» تعني أن موظفاً أكّد النشر بنفسه؛ ليست إثباتاً من المنصة. نتائج الحملات في النظام تأتي من طلبات وكوبونات المتجر، وليست مشاهدات أو تفاعلات اجتماعية.', '“Manually published” means a staff member confirmed the action; it is not verified by the platform. Campaign results come from storefront orders and coupons, not social impressions or engagement.')}</p></div><Link href="/admin/marketing/content" data-testid="link-channels-content" className="mt-8 inline-flex w-fit items-center gap-2 text-sm font-semibold text-accent hover:underline">{t('العودة إلى المحتوى', 'Back to content')}<ArrowUpRight className="h-4 w-4" /></Link></section></div>
  </MarketingShell>;
}